GET http://localhost:3000/

###
GET http://localhost:3000/book


###
POST http://localhost:3000/register
content-type: application/json

{
    "key":"104",
    "email": "rinkon@gmail.com",
    "password": "rinkon1234",
    "name":"Rinkon"
}

###
POST http://localhost:3000/depositmoney
content-type: application/json

{
    "key":"103",
    "amount":"1500"
}

###
POST http://localhost:3000/withdrawmoney
content-type: application/json

{
    "key":"104",
    "password": "rinkon1234",
    "amount":"160"
}

###
POST http://localhost:3000/sendmoney
content-type: application/json

{
    "from_key":"102",
    "to_key":"100",
    "from_password":"rinkon1234",
    "amount":"57"
}

###
